language: scala
sudo: false
jdk:
  - openjdk8
scala:
  - 2.10.4
   
script:
  - sbt -sbt-version 0.13.15 -scala-version $TRAVIS_SCALA_VERSION test

notifications:
  slack:
    rooms:
      - targetprocess:o25eQr7bOyzMrwknqPXWsXQx#buildboard

services:
  - mongodb
