language: scala
sudo: false
jdk:
  - openjdk8
scala:
  - 2.11.11
   
script:
  - sbt -sbt-version 0.13.18 -scala-version $TRAVIS_SCALA_VERSION test

notifications:
  slack:
    rooms:
      - targetprocess:o25eQr7bOyzMrwknqPXWsXQx#buildboard

services:
  - mongodb

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
