/// <reference path='libs/md5.ts' />
/// <reference path='libs/jquery.d.ts' />
/// <reference path='libs/angular.d.ts' />
/// <reference path='libs/angular-ui-router.d.ts' />
/// <reference path='libs/underscore.d.ts' />
/// <reference path='interfaces/JsRoutes.d.ts' />
/// <reference path='services/HttpServiceNotificationDecorator.ts'/>
/// <reference path='services/BackendService.ts'/>
/// <reference path='services/LoggedUserService.ts'/>

/// <reference path='services/ModelProvider.ts'/>

/// <reference path='models/Branch.ts' />
/// <reference path='filters/Filters.ts' />
/// <reference path='interfaces/IBuildBoardWindow.ts' />
/// <reference path='interfaces/IBuildBoardRoadParamsService.ts'/>
/// <reference path='controllers/StatusController.ts'/>
/// <reference path='controllers/IBranchScope.ts'/>
/// <reference path='controllers/BranchesController.ts' />
/// <reference path='controllers/BranchController.ts' />
/// <reference path='controllers/BranchLineController.ts' />
/// <reference path='controllers/HeaderController.ts' />
/// <reference path='controllers/RunController.ts' />
/// <reference path='controllers/TestCaseController.ts' />
/// <reference path='controllers/ConfigController.ts' />
/// <reference path='directives/EntityTitle.ts' />
/// <reference path='directives/EntityState.ts' />
/// <reference path='directives/BuildStatus.ts' />
/// <reference path='Application.ts' />
