/// <reference path='libs/jquery.d.ts' />
/// <reference path='libs/angular.d.ts' />
/// <reference path='libs/angular-route.d.ts' />
/// <reference path='libs/underscore.d.ts' />
/// <reference path='interfaces/JsRoutes.ts' />
/// <reference path='services/BackendService.ts'/>
/// <reference path='models/Branch.ts' />
/// <reference path='filters/Filters.ts' />
/// <reference path='interfaces/IBranchesScope.ts' />
/// <reference path='interfaces/IBuildBoardWindow.ts' />
/// <reference path='interfaces/IBuildBoardRoadParamsService.ts'/>
/// <reference path='controllers/BranchControllerBase.ts'/>
/// <reference path='controllers/BranchesController.ts' />
/// <reference path='controllers/BranchController.ts' />
/// <reference path='controllers/BranchLineController.ts' />
/// <reference path='models/User.ts' />
/// <reference path='directives/EntityTitle.ts' />
/// <reference path='directives/Panel.ts' />
/// <reference path='directives/EntityState.ts' />
/// <reference path='Application.ts' />