/// <reference path='libs/jquery.d.ts' />
/// <reference path='libs/angular.d.ts' />
/// <reference path='libs/angular-ui-router.d.ts' />
/// <reference path='libs/underscore.d.ts' />
/// <reference path='interfaces/JsRoutes.d.ts' />
/// <reference path='services/BackendService.ts'/>
/// <reference path='services/BranchesService.ts'/>
/// <reference path='services/LoggedUserService.ts'/>
/// <reference path='models/Branch.ts' />
/// <reference path='filters/Filters.ts' />
/// <reference path='interfaces/IBuildBoardWindow.ts' />
/// <reference path='interfaces/IBuildBoardRoadParamsService.ts'/>
/// <reference path='controllers/BranchControllerBase.ts'/>
/// <reference path='controllers/BranchesController.ts' />
/// <reference path='controllers/BranchController.ts' />
/// <reference path='controllers/BranchLineController.ts' />
/// <reference path='controllers/HeaderController.ts' />
/// <reference path='controllers/TestCasePackageController.ts' />
/// <reference path='directives/EntityTitle.ts' />
/// <reference path='directives/Panel.ts' />
/// <reference path='directives/EntityState.ts' />
/// <reference path='directives/BuildStatus.ts' />
/// <reference path='Application.ts' />